baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'ananke'
title = 'ABC Widgets, Inc.'
enableEmoji=true
[params]
  subtitle = 'The Best Widgets on Earth'
  [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'

[frontmatter]
 date= ['myDate', ':default_time']

